# Generated by Django 4.0.4 on 2022-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Disikes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active post'),
        ),
    ]
